### ISSUE TITLE
Removing expired cookies.

### ISSUE THREAD

**Issue by lucasdiedrich** [lucasdiedrich/node-freeipa#11]
Before saving the cache stores from cookies it should verify the expired ones and remove them.

**Comment by nmccready** [comment]
This is a pretty big problem as well as any cookie that is stored with invalid credentials should also be removed.

Either cases should cause removal.
- initial login failure
- or later login where something is expired

**Comment by lucasdiedrich** [comment]
@nmccready i can confirm that this must be done as soon as possible, but, invalid credentials will not ever be saved over cookie db.

What is the history case for this?

**Comment by nmccready** [comment]
@lucasdiedrich its hard to determine what exactly is happening. But utilizing the `passport-freeipa` module we're seeing problems when multiple people try to login at the same time. 

Not sure if this is related to trying to access the cache file and corrupting it or not. Might help to have an option to not cache it at all.

🤷‍♂

**Comment by nmccready** [comment]
Another problem is the error when loginng in is very obtuse with [`JSON.parse(body)`](https://github.com/lucasdiedrich/node-freeipa/blob/master/src/lib/Request.js#L49) failing and just giving that error instead of `failed login` bad password or something more meaningful.

Not sure if this is something you can actually determine from the IPA reply or not.

**Comment by nmccready** [comment]
If this does lead to asynchronous issues with hitting the cached json file you might want to take a look at rocket-store.
I found via https://www.npmjs.com/package/express-session-rsdb -> https://www.npmjs.com/package/rocket-store

**Comment by lucasdiedrich** [comment]
@nmccready this lib is totally needing an rewrite, planing to do this week or month, infortunetly i don't have to much time. But, is in your freeipa environment using the default kerberos expire date? 24hrs.

About the login page it don't return an valid error because Freeipa servers also don't return it, but it should be treated as well.

I'll be updating this lib **ASAP**.

**Comment by nmccready** [comment]
I started using rocket store for the session management and I haven't run into nearly the amount of problems I was having. Anyway, things might not be as urgent as they appear.

**Comment by nmccready** [comment]
Ugh well I am seeing problems again and I guess it is session expiration related. In a nutshell if the login begins failing through `node-freeipa`; if I go and login directly through FreeIPAs portal it invalidates the cache and then I can login.

Example of the error prior to being resolved by forcing login via portal.
```
{
  body: '<html>\n' +
    '<head>\n' +
    '<title>401 Unauthorized</title>\n' +
    '</head>\n' +
    '<body>\n' +
    '<h1>Invalid Authentication</h1>\n' +
    '<p>\n' +
    '<strong>Insufficient access: SASL(-1): generic failure: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Credential cache is empty)</strong>\n' +
    '</p>\n' +
    '</body>\n' +
    '</html>'
}
Error: Freeipa: problem with request: Unexpected token < in JSON at position 0
    at IncomingMessage.<anonymous> (/app/node_modules/node-freeipa/src/lib/Request.js:66:18)
```

**Comment by nmccready** [comment]
I'm going to decrease the expires time significantly and see if this helps.

**Comment by lucasdiedrich** [comment]
> Ugh well I am seeing problems again and I guess it is session expiration related. In a nutshell if the login begins failing through `node-freeipa`; if I go and login directly through FreeIPAs portal it invalidates the cache and then I can login.
> 
> Example of the error prior to being resolved by forcing login via portal.
> 
> ```
> {
>   body: '<html>\n' +
>     '<head>\n' +
>     '<title>401 Unauthorized</title>\n' +
>     '</head>\n' +
>     '<body>\n' +
>     '<h1>Invalid Authentication</h1>\n' +
>     '<p>\n' +
>     '<strong>Insufficient access: SASL(-1): generic failure: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Credential cache is empty)</strong>\n' +
>     '</p>\n' +
>     '</body>\n' +
>     '</html>'
> }
> Error: Freeipa: problem with request: Unexpected token < in JSON at position 0
>     at IncomingMessage.<anonymous> (/app/node_modules/node-freeipa/src/lib/Request.js:66:18)
> ```

@nmccready since version 2.2.0 this will no longer happen, now, it will resolv into {error: FREEIPA.AUTH_ERROR}. Actually everything will resolve into an error, this makes easier to handle this kind of stuff. 

About the expires time, it should be exactly what you have configured into your Freeipa Server, what is your kerberos ticket lifetime?

Right now i'm debugging this.

**Comment by lucasdiedrich** [comment]
@nmccready since version 2.2.1 it will remove expired cookie on cache verification, i really doesn't know why i did not make that before. But, i will try to test this over concurrent logins.

Just remember, in the app we deal the expire time in minute, and in kerberos policy it uses seconds.

![image](https://user-images.githubusercontent.com/817482/74036652-6fa40480-499b-11ea-9665-e99438b00184.png)

Thanks.

**Comment by nmccready** [comment]
Yeah so my expires time was the default and I think that was too long and probably the root of the problem. I appreciate you digging into this.

**Comment by nmccready** [comment]
Also can you start utilizing `npm version`? That way you're git repo will be in sync with the releases on gitlab. It also make it much easier to stay within the confines of semver .

**Comment by lucasdiedrich** [comment]
> It also make it much easier to stay within the confines of semver

I didn't get the idea, does using npm version change anything more, anyway, going to research about that. Next version will be async/await ready. Closing the issue now.

thanks.

**Comment by nmccready** [comment]
https://docs.npmjs.com/cli/version

Its amazing.

```
❯ npm version --help
npm version [<newversion> | major | minor | patch | premajor | preminor | prepatch | prerelease [--preid=<prerelease-id>] | from-git]
(run in package dir)
'npm -v' or 'npm --version' to print npm version (6.13.6)
'npm view <pkg> version' to view a package's published version
'npm ls' to inspect current package/dependency versions
```

**Comment by lucasdiedrich** [comment]
@nmccready https://www.npmjs.com/package/node-freeipa/v/2.3.0

First version using `npm version`, i'm going to get used to it.  Thanks.
