### ISSUE TITLE
Promise always pending?

### ISSUE THREAD

**Issue by wolf-allywilson** [lucasdiedrich/node-freeipa#29]
I'm attempting to use this in a project I'm working on, but I'm stumbling at the first hurdle it seems. I can't seem to get the Promise to return anything? It just stays in pending.

```
const ipa = require('node-freeipa');
const ipaOpts = {
    server: 'my.freeipa.org',
    auth: {
        user: 'myusername',
        pass: 'mypassword',
    },
};
ipa.configure(ipaOpts);



ipa.json_metadata.then((result) => {
    console.log(result);
});
```

That errors with:

> Uncaught TypeError: ipa.json_metadata.then is not a function

`ipa.json_metadata();`
returns:
> Promise { \<pending\> }

node-freeipa version: 2.3.5
ipa server version: 4.9.6
testing on: macOS monterey

I've monitored network traffic and can see a connection to the server from my machine when i execute:
 `ipa.json_metadata();`
It's all HTTPS, so can't really decipher it.

Any help much appreciated!

**Comment by lucasdiedrich** [comment]
Hey @wolf-allywilson , have you tried to await the the ipa.json_metadata()?

like in the docs?
![image](https://user-images.githubusercontent.com/817482/154319674-d236dbd9-1eb4-4976-98d3-8b133b6c5a39.png)

**Comment by wolf-allywilson** [comment]
Thanks for getting back to me. 

After posting and testing around somewhat, I seen this issue: https://github.com/lucasdiedrich/node-freeipa/issues/15

So I tried it with a different user and it worked. I removed the cookie and tried with the original user and it worked again.

Sorry for wasting your time.

**Comment by lucasdiedrich** [comment]
@wolf-allywilson don't worry about that, any doubts or improvements, please fell free to send a issue.
