### ISSUE TITLE
Override CACHE_FOLDER?

### ISSUE THREAD

**Issue by wolf-allywilson** [lucasdiedrich/node-freeipa#30]
Hello (again),

I'm trying to get node-freeipa running in an AWS Lambda function but hitting a stumbling block when attempting to authenticate due to this error:

> Error: EROFS: read-only file system, mkdir '/.tmp'

Which I can understand as AWS Lambda only allows writes to '/tmp' and not the current working directory (/var/task)

I **believe** this is caused by this:

```
    // asset-input/node_modules/node-freeipa/src/lib/Session.js
    var require_Session = __commonJS({
      "asset-input/node_modules/node-freeipa/src/lib/Session.js"(exports2, module2) {
        var fs2 = require("fs");
        var path2 = require("path");
        var CACHE_FOLDER = path2.join(__dirname, "../../", ".tmp");
```

But struggling to be sure. Is there a way to simply override that value in the auth parameters or similar?

Thanks for any help.

**Comment by wolf-allywilson** [comment]
I've raised this [PR](https://github.com/lucasdiedrich/node-freeipa/pull/31) to address this, please let me know if any questions or concerns.

**Comment by lucasdiedrich** [comment]
@wolf-allywilson thank for the PR, i'll try to make this more platform agnostic trying to add this as a freeipa configuration itself.

**Comment by lucasdiedrich** [comment]
@wolf-allywilson thanks for the incredible feature! 

we now have a custom option at configure where we can set the location of the cookiefolder! :rocket::rocket::rocket:
